### DISCUSSION TITLE
The documentation thread

### DISCUSSION THREAD

**Discussion by uogbuji** [OoriData/Toolio#21] [General]
Just all sorts of ongoing thoughts & updates re Toolio docs. I picked MkDocs for its simplicity & markdown friendliness. I'll start with the initial setup.

Changed to my Toolio github checkout and In the virtual env I use for Toolio dev:

```sh
pip install mkdocs
pip install mkdocs-material
mkdocs new .
mv docs doc
```

Had to update `mkdocs.yml`. `docs_dir` because I was using the non-default dir, and then I just touched up a few other bits.

```yaml
docs_dir: doc
site_name: Toolio—Schema-controlled responses and tool-calling for LLMs on Mac
theme:
  name: material
```

Local preview of docs (starts a dev server for doc at http://127.0.0.1:8888/):

```sh
mkdocs serve -a localhost:8888
```

Started by just copying the contents of README to an initial page.

```sh
cp README.md doc/index.md
```

Started fleshing things out from there.
