### DISCUSSION TITLE
Simpler schema format

### DISCUSSION THREAD

**Discussion by uogbuji** [OoriData/Toolio#27] [Ideas]
Right now our schema support, inherited from [llm-structured-output](https://github.com/otriscon/llm-structured-output), is JSON-only (a subset of [JSON Schema](https://json-schema.org/)). Works great, but JSON is super token hungry. For example, here is an elaborated version of the country/continent schema used in the Toolio README.

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "description": "A list of countries with their names and continents",
  "items": {
    "type": "object",
    "description": "Detailed information about a single country",
    "properties": {
      "name": {
        "type": "string",
        "description": "The full name of the country",
        "examples": [
          "Canada",
          "Egypt"
        ]
      },
      "continent": {
        "type": "string", 
        "description": "The continent where the country is primarily located",
        "examples": [
          "North America",
          "Africa"
        ],
        "enum": [
          "North America",
          "South America", 
          "Europe",
          "Asia",
          "Africa",
          "Oceania",
          "Antarctica"
        ]
      }
    },
    "required": ["name", "continent"],
    "additionalProperties": false
  }
}
```

Made-up example of a YAML equivalent (created with help from Claude & tweaking the result):

```yaml
version: 1.0
type: list[country]
description: Lightweight representation of countries with minimal structure

constraints:
  country:
    required_fields: [name, continent]
    name:
      type: str
      description: Full name of the country
      examples: [Canada, Egypt]
    continent:
      type: str
      description: Primary continent of the country
      valid_values: 
        - North America
        - South America
        - Europe
        - Asia
        - Africa
        - Oceania
        - Antarctica

example:
  - name: Canada
    continent: North America
  - name: Egypt
    continent: Africa
```

* JSON Schema Token Count: 222
* YAML Schema Token Count: 144
(Counts from [tiktoken](https://github.com/openai/tiktoken) with `cl100k_base` encoding—same as GPT-4) 

Think it would be great to implement code in Toolio to read the latter as if it were the former, providing not only a friendlier way to express the schema, but a less tokens-greedy one.
